name: Roadshow_CICD
on:
  push:
    branches:
      - main
jobs:

  compile:    
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v4
    - run: mkdir -p /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/Data
    - run: open -W /Applications/4D/20/4D_20_R4/4D.app --args /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/RoadShow-CICD-Source/Project/Roadshow_CICD.4DProject --create-data /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/Data/data.4DD --user-param "compile"
    - run: |
        compilationResult='cat compilationResult.txt'
        echo $compilationResult
        headCompilation='head -n 1 compilationResult.txt'
        rm compilationResult.txt
        if [ "$headCompilation" = "Syntax check failed" ]
        then
          exit 1
        fi

  test:
    needs: compile
    runs-on: [self-hosted]

    steps: 
      - run: open -W /Applications/4D/20/4D_20_R4/4D.app --args /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/RoadShow-CICD-Source/Project/Roadshow_CICD.4DProject --create-data /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/Data/data.4DD --user-param "test"
      - run: |
          UTestResult='cat UTestResult.txt'
          echo $UTestResult
          value='head -n 1 UTestResult.txt'
          rm UTestResult.txt
          if [ "$value" = "Unit tests failed" ]
          then
            exit 1
          fi

  build:
    needs: test
    runs-on: [self-hosted]

    steps: 
      - run: open -W /Applications/4D/20/4D_20_R4/4D.app --args /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/RoadShow-CICD-Source/Project/Roadshow_CICD.4DProject --create-data /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/Data/data.4DD --user-param "build"
      - run: |
          buildResult='cat buildResult.txt'
          echo $buildResult
          value='head -n 1 buildResult.txt'
          rm buildResult.txt
          if [ "$value" = "build failed" ]
          then
            exit 1
          fi

  deploy:
    needs: build
    runs-on: [self-hosted]

    steps:
      - run: mv /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/Build/Compiled\ Database/RoadShow2024 /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/Build/Compiled\ Database/RoadShow2024.4dbase
      - run: ditto -c -k --sequesterRsrc --keepParent /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/Build/Compiled\ Database/RoadShow2024.4dbase ../RoadShow2024.zip
      - run: mv /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/Build/Compiled\ Database/RoadShow2024.zip /Users/waynestewart/4D/Roadshow_2023-24/CI-CD/Runner/work/Deploy/RoadShow2024.zip
